name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for Finch
      uses: MatsMoll/action-finch@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_SHA: ${{ secrets.GITHUB_SHA }}
        FINCH_CONFIG: "finch-config.yml"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
