name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: GitHub Action for Finch
      uses: MatsMoll/action-finch@master
    - name: Run tests
      run: swift test -v
